name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Poetry
      - name: Install Poetry
        run: |
          pip install poetry

      # Step 4: Install Dependencies
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: Lint with Ruff
      - name: Lint with Ruff
        run: |
          poetry run ruff check .

      # Step 6: Check formatting with Black
      - name: Check formatting with Black
        run: |
          poetry run black --check .

      # Step 7: Static Type Checking with mypy
      - name: Static type checking with mypy
        run: |
          poetry run mypy .

      # Step 8: Run Tests with pytest
      - name: Run tests with pytest
        run: |
          poetry run pytest
